### ISSUE TITLE
Opening brackets incorrectly highlighted

### ISSUE THREAD

**Issue by frm** [ananthakumaran/tree-sitter-elixir#25]
The first bracket isn't captured as a tree-sitter highlight group. Example, using `:TSHighlightCapturesUnderCursor` from `nvim-treesitter/playground`:

<img width="363" alt="Screenshot 2021-06-28 at 11 45 20" src="https://user-images.githubusercontent.com/4325027/123624412-6b81bc80-d806-11eb-9e29-286fb6c3c583.png">

**Comment by ananthakumaran** [comment]
I think this should be raised to nvim-treesitter repo. You can check the AST produced [here](https://ananthakumaran.in/tree-sitter-elixir/). Apart from incorrect AST, issues related to other features should be raised to the editor package repo.

**Comment by frm** [comment]
Will do, thanks!
