### ISSUE TITLE
Treat strings tagged with @doc and @moduledoc as comments

### ISSUE THREAD

**Issue by pedro-gutierrez** [ananthakumaran/tree-sitter-elixir#26]
Hello, many thanks for this grammar, I recently moved to Neovim 0.5.0 + tree sitter and it does a pretty good job! 
One thing I miss from Neovim 0.4.4+vim-elixir plugin is the ability to have strings tagged as @moduledoc and @doc coloured as comments (in my case, it would be blue, rather than red):

<img width="311" alt="image" src="https://user-images.githubusercontent.com/12581/124633937-138e2a00-de86-11eb-89a7-873801191e2c.png">

I'd love to raise a PR myself in order to cover this, but honestly I don't even know where to start.

**Comment by ananthakumaran** [comment]
This part is controlled by the specific [query](https://github.com/nvim-treesitter/nvim-treesitter/blob/dff252d32abd1cb00b746bd2756eaa969a7e06ea/queries/elixir/highlights.scm#L130-L137).

```lisp
(unary_op
 operator: "@"
 (call (function_identifier) @attribute
       (heredoc
        [(heredoc_start)
         (heredoc_content)
         (heredoc_end)] @comment))
 (#any-of? @attribute "doc" "moduledoc"))
``` 
Changing the `@string` to `@comment` would do the trick. Though I don't know how exactly the query should be changed by the end user. This doc might help https://github.com/nvim-treesitter/nvim-treesitter#adding-queries

**Comment by ananthakumaran** [comment]
btw, I also would suggest to open an issue on nvim-treesitter and check if the change can be applied there

**Comment by pedro-gutierrez** [comment]
Awesome thank you!

**Comment by pedro-gutierrez** [comment]
The fix you suggested works very well although I am not sure my PR will get merged. So, for now I will be using my own fork of nvim-treesitter. In any case, many thanks for your help on this. I'll close this issue.
