### ISSUE TITLE
Query errors when running `:checkhealth nvim-treesitter`

### ISSUE THREAD

**Issue by mateusdeap** [ananthakumaran/tree-sitter-elixir#27]
`nvim -v` output
![image](https://user-images.githubusercontent.com/14188887/124919877-19daee00-dfcd-11eb-8546-6a995062aacd.png)

`:checkhealth nvim-tree-sitter` #Installation section
![image](https://user-images.githubusercontent.com/14188887/124920021-43941500-dfcd-11eb-96f6-efba4ec1148a.png)

The problem consists that I'm not getting any syntax highlighting for exs files, and the syntax highlighting for .ex files, although it exists, seems to be odd when compared to ruby or C. Treesitter complains that it failed to upload a uv_dlopen parser due to an unknown symbol in `elixir.so`:
![image](https://user-images.githubusercontent.com/14188887/124920252-86ee8380-dfcd-11eb-96ae-982cba42caa6.png)

I think it worthy of note that, if I copy the `elixir.so` file generated by following the instructions on this repo's README to the folder from where treesitter seems to be actually reading things (`~/.config/nvim/plugged/nvim-treesitter/parser/`), the errors go away, but I do not get any syntax highlighting for .exs files nor does the highlighting seem to change for .ex files.

Alternatively, If I install this parser following the docs at the treesitter repo, I start getting these errors again.

Seems to me that I might have setup something wrong... I'd really appreciate some guidance... the whole vim ecosystem is somewhat new to me.

Thanks in advance!

**Comment by ananthakumaran** [comment]
This should be raised to https://github.com/nvim-treesitter/nvim-treesitter. This repo only hosts the elixir parser and vim integration is handled by nvim-treesitter.

**Comment by mateusdeap** [comment]
I see. Very well then, thank you!
