### ISSUE TITLE
Fail to highlight all function parameters 

### ISSUE THREAD

**Issue by akash-akya** [ananthakumaran/tree-sitter-elixir#4]
With current master, we fail to highlight function parameters when the number of parameters are more.

**Examples**
Screenshots are generated from `tree-sitter highlight ... --html`. I can see the same behavior in Emacs.

<img width="373" alt="Screenshot 2021-04-04 at 2 23 16 PM" src="https://user-images.githubusercontent.com/9396022/113503744-5243d980-9551-11eb-9b53-dd0ff952fcb7.png">

This does not appear to happen in `tree-sitter-query-builder`, so guessing it happens only if we pass range

I'm not 100% sure of this, but my guess is that this is because of how our highlight query for function declaration is written. [There seems to be a limit on the number of buffered matches for `capture`](https://github.com/tree-sitter/tree-sitter/issues/634). I think in our case the function declaration query has large capture range (from `@keyword` to `@variable.parameter`). More about this [here](https://github.com/tree-sitter/tree-sitter/pull/644). 

Just for debugging, I update query by removing `@keyword` capture and that seems to work.

```diff
modified   queries/highlights.scm
@@ -24,9 +24,9 @@
 (call (identifier) @keyword
       (#match? @keyword "^(defmodule|defexception|defp|def|with|case|cond|raise|import|require|use|defmacrop|defmacro|defguardp|defguard|defdelegate|defstruct|alias|defimpl|defprotocol|defoverridable|receive|if|for|try|throw|unless|reraise|super|quote|unquote|unquote_splicing)$"))
 
-(call (identifier) @keyword
+(call (identifier)
       [(call
-        name: (identifier) @function
+        name: (identifier)
         (arguments
          [(identifier) @variable.parameter
           (_ !function !object !name (identifier) @variable.parameter)
@@ -51,7 +51,6 @@
         left: (identifier) @variable.parameter
         operator: _ @function
         right: (identifier) @variable.parameter)]
-      (#match? @keyword "^(defp|def|defmacrop|defmacro|defguardp|defguard|defdelegate)$")
       (#match? @variable.parameter "^[^_]"))
 
 (call (identifier) @keyword
```
<img width="385" alt="Screenshot 2021-04-04 at 2 24 46 PM" src="https://user-images.githubusercontent.com/9396022/113503768-8919ef80-9551-11eb-9a52-de9bac538171.png">

**Comment by ananthakumaran** [comment]
Seems like we are hitting some internal limit somewhere. Removing queries from `highlights.scm` improves the number of parameters being highlighted. I could get it to highlight 18 params if I remove all the queries except the params related.

**Comment by akash-akya** [comment]
Yes, but if you apply the changes I mentioned above without removing other queries, then it highlights more than 18 params (I tested till 50 params). So I think the capture range is affecting this. Maybe [these constants](https://github.com/tree-sitter/tree-sitter/blob/72143b17ff7ed617714e77ccd9a51e49bdecc9ed/lib/src/query.c#L15-L19)

**Comment by ananthakumaran** [comment]
This issue has been fixed in the last patch and we now have a [test](https://github.com/ananthakumaran/tree-sitter-elixir/blob/master/test/highlight/sandbox.ex#L1109) to catch any regression.
